#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
require 5.6.0;
use strict;
use warnings;
use Thrift;

package Color;
use constant RED => 1;
use constant YELLOW => 2;
use constant GREEN => 3;
use constant BLUE => 4;
1;
