#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
package tutorial::Constants;
require 5.6.0;
use strict;
use warnings;
use Thrift;


use constant INT32CONSTANT => 9853;

use constant MAPCONSTANT => {
"hello" => "world",
"goodnight" => "moon",
};

1;
