#!/usr/bin/perl

my $n = <>;
for(1..(($n/80)+(($n%80)&&1))) {
	$_ = <>; # probably should save this, but the puzzle doesn't require it ;)
}
my $g = <>;
my @p = ();
for(1..$g) {
	$_ = <>;
	my($start,$stop,$score) = split;
	$p[$start] = [] unless $p[$start];
	push @{$p[$start]}, [$stop,$score];
}
sub f {
	my($start) = @_;
	my @r = (0);
	while($start < $n) {
		if ($p[$start]) {
			for (@{$p[$start]}) {
				my($stop,$score) = @$_;
				push @r, map {$score+$_} f($stop+1);
			}
		}
		++$start;
	}
	@r = sort {$a <=> $b} @r;
	return pop @r;
}
print f(0)."\n";
